# Generated by Django 4.1.7 on 2023-03-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('registration_link', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datatime', models.DateTimeField()),
                ('max_attendance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster_path', models.CharField(max_length=500)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='event_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField()),
                ('student_id', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
            ],
        ),
    ]
