# Generated by Django 4.1.7 on 2023-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_path',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(),
        ),
    ]
