# Generated by Django 4.1.7 on 2023-03-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_poster_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='event_attendance',
            old_name='event_id',
            new_name='event',
        ),
    ]
