# Generated by Django 4.1.7 on 2023-03-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_club_id_event_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_datatime',
            new_name='end_datetime',
        ),
    ]
