# Generated by Django 4.1.7 on 2023-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_end_datatime_event_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
