# Generated by Django 4.1.7 on 2023-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_registration_link_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_attendance',
            field=models.IntegerField(null=True),
        ),
    ]
