# Generated by Django 4.1.7 on 2023-03-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_max_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_attendance',
            name='registered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
