# Generated by Django 4.1.7 on 2023-03-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_attendance_registered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_attendance',
            old_name='event',
            new_name='event_id',
        ),
    ]
