# Generated by Django 4.1.7 on 2023-03-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_club_officer_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('headquarter', models.CharField(max_length=50)),
                ('logo_path', models.CharField(max_length=500)),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='club_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
                ('club_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.club_officer')),
            ],
        ),
    ]
