# Generated by Django 4.1.7 on 2023-03-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='supervisor_id',
            new_name='supervisor',
        ),
    ]
