# Generated by Django 4.1.7 on 2023-03-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_rename_supervisor_id_club_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_management',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='club_management',
            old_name='club_officer_id',
            new_name='club_officer',
        ),
    ]
